### ISSUE TITLE
do_moves

### ISSUE THREAD

**Issue by antonmedv** [mpcal/shashki-ai#1]
Hi! 

This is an awesome project! Really cool. 

I was reading the code, but how moves dons? I understand how normal moves done, but how capturing moves are done?

**Comment by mpcal** [comment]
Hi Anton, 

Thanks :) but it's still super basic.

Capturing moves are the same as non-capturing moves. The logic is sort of two-fold: first we generate all feasible moves, capturing or not, cf.`valid_moves()`. Later, when we execute a move with `do_move_bk()` or `do_move_wt()` we always clear the squares that we jump over. This way we capture any opponent token that may or may not be there.

Making any sense? :)

**Comment by antonmedv** [comment]
Yes, make sense. And what if there a few captures in one move?

**Comment by mpcal** [comment]
That's the "ply" concept where a ply consists of one or more moves. A multi-move ply only occurs in presence of a capture while a capture doesn't necessarily lead to multi-move ply.

The respective logic is [here](https://github.com/mpcal/shashki-ai/blob/969436624a128c0566aff8dafa701ff21dbc8222/src/game.cc#L17-L28), inside `play_a_ply()`.

**Comment by antonmedv** [comment]
Got it. Thanks for explanation. Awesome project.

**Comment by mpcal** [comment]
Thanks for your interest. Always happy to help if you have more questions.
